server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  custom:
    contextPath: /auth
    adminUser:
      username: fluentlab-admin
      password: 123456
      create-admin-user-enabled: true
    importRealmPath: fluentlab-realm.json