server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: fluentlab-admin
      password: 123456
    realmImportFile: fluentlab-realm.json